name: demoapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  timeago: ^3.3.0
  shared_preferences: ^2.0.0
  intl: ^0.19.0
  onboarding: ^4.0.2
  smooth_page_indicator: ^1.0.0+2
  share_plus: ^9.0.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3

  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/page1.png
    - assets/page2.png
    - assets/page3.png
